ARG NODE_VERSION=16
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-buster-slim as base

WORKDIR /app

COPY lerna.json init.js ./
COPY package.json yarn.lock ./

COPY packages /app/packages

RUN yarn install
RUN yarn lerna bootstrap
RUN cd packages/client && yarn build:ssr && yarn build

EXPOSE $SERVER_PORT