export enum UserActionType {
  REQUEST_SESSION = 'REQUEST_SESSION',
  INIT_SESSION = 'INIT_SESSION',
  RECIEVE_SESSION = 'RECIEVE_SESSION',
  LOGOUT_SESSION = 'LOGOUT_SESSION',
  ERROR_SESSION = 'ERROR_SESSION',
  CHECK_SESSION_FAIL = 'CHECK_SESSION_FAIL',
}
